"""Tunable knobs of the Ornith families: the 9B dense GDN hybrid and the
35B-A3B MoE, both on DFlash2 drafts."""

from .base import (
    ADAPTIVE_PROPOSALS,
    DFLASH_POOL,
    DRAFT_BYPASS,
    DRAFT_BYPASS_EXPECT,
    GDN_CHUNKED,
    GGUF_PACKED,
    HEAD_FUSED,
    ICB_OFF,
    MOE_PACKED_OFF,
    MOE_UNION,
    MTL4,
    NGRAM_DRAFT_EXPECT,
    NGRAM_TREE_MIN,
    NGRAM_WARMUP,
    NO_FUSED_GATE,
    PATCHABLE_OFF,
    PREFILL_FAST_INT8,
    PREPARED_CACHE_OFF,
    PROPOSAL_CAP,
    SUBMIT_AHEAD,
    VERIFY_TREE,
    TunableKnobs,
)

_COMMON = (
    VERIFY_TREE,
    DFLASH_POOL,
    GDN_CHUNKED,
    PREFILL_FAST_INT8,
    ADAPTIVE_PROPOSALS,
    DRAFT_BYPASS,
    DRAFT_BYPASS_EXPECT,
    PROPOSAL_CAP,
    HEAD_FUSED,
    MTL4,
    GGUF_PACKED,
    SUBMIT_AHEAD,
    ICB_OFF,
    PREPARED_CACHE_OFF,
    PATCHABLE_OFF,
    NO_FUSED_GATE,
    NGRAM_DRAFT_EXPECT,
    NGRAM_WARMUP,
    NGRAM_TREE_MIN,
)

TUNABLE = (
    TunableKnobs("Ornith-1.5-9B", _COMMON),
    TunableKnobs("Ornith-1.5-35B-A3B", _COMMON + (MOE_UNION, MOE_PACKED_OFF)),
)
